title: "Math Compendium"
description: "Competitive mathematics techniques and notes"
theme: minima
baseurl: "/math-compendium"
url: "https://thekunalprashant.github.io"

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed

words_per_minute: 200

# Custom variables
popular_topics:
  - Value Substitution